//  Define types of Actions
const ADD_USER = {
  REQUEST: 'ADD_USER_REQUEST',
  SUCCESS: 'ADD_USER_SUCCES',
  FAIL: 'ADD_USER_FAIL',
};
const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAIL: 'LOGIN_FAIL',
};
const FETCH_DONORS = {
  REQUEST: 'FETCH_DONORS_REQUEST',
  SUCCESS: 'FETCH_DONORS_SUCCESS',
  FAIL: 'FETCH_DONORS_FAIL',
};
const FETCH_REQUESTS = {
  REQUEST: 'FETCH_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_REQUESTS_SUCCESS',
  FAIL: 'FETCH_REQUESTS_FAIL',
};
const FETCH_MY_ADMIN_APPROVED_REQUESTS = {
  REQUEST: 'FETCH_MY_ADMIN_APPROVED_REQUEST',
  SUCCESS: 'FETCH_MY_ADMIN_APPROVED_SUCCESS',
  FAIL: 'FETCH_MY_ADMIN_APPROVED_FAIL',
};
const FETCH_MY_ADMIN_REJECTED_REQUESTS = {
  REQUEST: 'FETCH_MY_ADMIN_REJECTED_REQUEST',
  SUCCESS: 'FETCH_MY_ADMIN_REJECTED_SUCCESS',
  FAIL: 'FETCH_MY_ADMIN_REJECTED_FAIL',
};
const FETCH_MY_DONOR_APPROVED_REQUESTS = {
  REQUEST: 'FETCH_MY_DONOR_APPROVED_REQUEST',
  SUCCESS: 'FETCH_MY_DONOR_APPROVED_SUCCESS',
  FAIL: 'FETCH_MY_DONOR_APPROVED_FAIL',
};
const FETCH_MY_DONOR_REJECTED_REQUESTS = {
  REQUEST: 'FETCH_MY_DONOR_REJECTED_REQUEST',
  SUCCESS: 'FETCH_MY_DONOR_REJECTED_SUCCESS',
  FAIL: 'FETCH_MY_DONOR_REJECTED_FAIL',
};
const FETCH_ADMIN_REQUESTS = {
  REQUEST: 'FETCH_ADMIN_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_ADMIN_REQUESTS_SUCCESS',
  FAIL: 'FETCH_ADMIN_REQUESTS_FAIL',
};
const FETCH_DONOR_REQUESTS = {
  REQUEST: 'FETCH_DONOR_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_DONOR_REQUESTS_SUCCESS',
  FAIL: 'FETCH_DONOR_REQUESTS_FAIL',
};
const FETCH_ADMIN_APPROVED_REQUESTS = {
  REQUEST: 'FETCH_ADMIN_APPROVED_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_ADMIN_APPROVED_REQUESTS_SUCCESS',
  FAIL: 'FETCH_ADMIN_APPROVED_REQUESTS_FAIL',
};
const FETCH_ADMIN_REJECTED_REQUESTS = {
  REQUEST: 'FETCH_ADMIN_REJECTED_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_ADMIN_REJECTED_REQUESTS_SUCCESS',
  FAIL: 'FETCH_ADMIN_REJECTED_REQUESTS_FAIL',
};
const FETCH_DONOR_APPROVED_REQUESTS = {
  REQUEST: 'FETCH_DONOR_APPROVED_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_DONOR_APPROVED_REQUESTS_SUCCESS',
  FAIL: 'FETCH_DONOR_APPROVED_REQUESTS_FAIL',
};
const FETCH_DONOR_REJECTED_REQUESTS = {
  REQUEST: 'FETCH_DONOR_REJECTED_REQUESTS_REQUEST',
  SUCCESS: 'FETCH_DONOR_REJECTED_REQUESTS_SUCCESS',
  FAIL: 'FETCH_DONOR_REJECTED_REQUESTS_FAIL',
};
const MAKE_REQUEST = {
  REQUEST: 'MAKE_REQUEST_REQUEST',
  SUCCESS: 'MAKE_REQUEST_SUCCESS',
  FAIL: 'MAKE_REQUEST_FAIL',
};
const ADMIN_APPROVES_REQUEST = {
  REQUEST: 'ADMIN_APPROVES_REQUEST_REQUEST',
  SUCCESS: 'ADMIN_APPROVES_REQUEST_SUCCESS',
  FAIL: 'ADMIN_APPROVES_REQUEST_FAIL',
};
const ADMIN_REJECTS_REQUEST = {
  REQUEST: 'ADMIN_REJECTS_REQUEST_REQUEST',
  SUCCESS: 'ADMIN_REJECTS_REQUEST_SUCCESS',
  FAIL: 'ADMIN_REJECTS_REQUEST_FAIL',
};
const DONOR_APPROVES_REQUEST = {
  REQUEST: 'DONOR_APPROVES_REQUEST_REQUEST',
  SUCCESS: 'DONOR_APPROVES_REQUEST_SUCCESS',
  FAIL: 'DONOR_APPROVES_REQUEST_FAIL',
};
const DONOR_REJECTS_REQUEST = {
  REQUEST: 'DONOR_REJECTS_REQUEST_REQUEST',
  SUCCESS: 'DONOR_REJECTS_REQUEST_SUCCESS',
  FAIL: 'DONOR_REJECTS_REQUEST_FAIL',
};

export {
  ADD_USER,
  LOGIN,
  FETCH_DONORS,
  FETCH_REQUESTS,
  FETCH_MY_ADMIN_APPROVED_REQUESTS,
  FETCH_MY_ADMIN_REJECTED_REQUESTS,
  FETCH_MY_DONOR_APPROVED_REQUESTS,
  FETCH_MY_DONOR_REJECTED_REQUESTS,
  FETCH_ADMIN_REQUESTS,
  FETCH_DONOR_REQUESTS,
  FETCH_ADMIN_APPROVED_REQUESTS,
  FETCH_ADMIN_REJECTED_REQUESTS,
  FETCH_DONOR_APPROVED_REQUESTS,
  FETCH_DONOR_REJECTED_REQUESTS,
  MAKE_REQUEST,
  ADMIN_APPROVES_REQUEST,
  ADMIN_REJECTS_REQUEST,
  DONOR_APPROVES_REQUEST,
  DONOR_REJECTS_REQUEST,
};
