//  Define types of Actions
const ADD_USER = {
  REQUEST: 'ADD_USER_REQUEST',
  SUCCESS: 'ADD_USER_SUCCES',
  FAIL: 'ADD_USER_FAIL',
};
const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAIL: 'LOGIN_FAIL',
};
const FETCH_DONORS = {
  REQUEST: 'FETCH_DONORS_REQUEST',
  SUCCESS: 'FETCH_DONORS_SUCCESS',
  FAIL: 'FETCH_DONORS_FAIL',
};
export { ADD_USER, LOGIN, FETCH_DONORS };
